//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskId { get; set; }
        public string TaskName { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerRole CustomerRole { get; set; }
        public virtual StatusTask StatusTask { get; set; }
    }
}
