//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASU_AVIA_Context : DbContext
    {
        public ASU_AVIA_Context()
            : base("name=ASU_AVIA_Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Der_btp> Der_btp { get; set; }
        public virtual DbSet<Der_izd> Der_izd { get; set; }
        public virtual DbSet<Dokum_Obosnov> Dokum_Obosnov { get; set; }
        public virtual DbSet<Gos_ree> Gos_ree { get; set; }
        public virtual DbSet<GOST_mater> GOST_mater { get; set; }
        public virtual DbSet<GR_RAZDIZD> GR_RAZDIZD { get; set; }
        public virtual DbSet<Grupp> Grupp { get; set; }
        public virtual DbSet<Image_old> Image_old { get; set; }
        public virtual DbSet<Image_old_v2> Image_old_v2 { get; set; }
        public virtual DbSet<Konserv> Konserv { get; set; }
        public virtual DbSet<M_Poverk> M_Poverk { get; set; }
        public virtual DbSet<Mark_mater> Mark_mater { get; set; }
        public virtual DbSet<Nazn_prib> Nazn_prib { get; set; }
        public virtual DbSet<Nm_mater> Nm_mater { get; set; }
        public virtual DbSet<Nm_prib> Nm_prib { get; set; }
        public virtual DbSet<Nm_vidiz> Nm_vidiz { get; set; }
        public virtual DbSet<Period_pover> Period_pover { get; set; }
        public virtual DbSet<Podgr_prib> Podgr_prib { get; set; }
        public virtual DbSet<Podgrupp> Podgrupp { get; set; }
        public virtual DbSet<Predpr_izg> Predpr_izg { get; set; }
        public virtual DbSet<Predpr_Postav> Predpr_Postav { get; set; }
        public virtual DbSet<Raz_det> Raz_det { get; set; }
        public virtual DbSet<Rod_poverk> Rod_poverk { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Role_Mapping> Role_Mapping { get; set; }
        public virtual DbSet<Sort_Mater> Sort_Mater { get; set; }
        public virtual DbSet<Spr_agr> Spr_agr { get; set; }
        public virtual DbSet<Spr_balsch> Spr_balsch { get; set; }
        public virtual DbSet<Spr_cen_mater> Spr_cen_mater { get; set; }
        public virtual DbSet<Spr_cena_del> Spr_cena_del { get; set; }
        public virtual DbSet<Spr_cex> Spr_cex { get; set; }
        public virtual DbSet<Spr_cex_prizn> Spr_cex_prizn { get; set; }
        public virtual DbSet<Spr_dse> Spr_dse { get; set; }
        public virtual DbSet<Spr_eizm> Spr_eizm { get; set; }
        public virtual DbSet<Spr_GR_Mater> Spr_GR_Mater { get; set; }
        public virtual DbSet<Spr_GR_tematik> Spr_GR_tematik { get; set; }
        public virtual DbSet<Spr_kdan> Spr_kdan { get; set; }
        public virtual DbSet<Spr_kgr> Spr_kgr { get; set; }
        public virtual DbSet<Spr_klass_tochn> Spr_klass_tochn { get; set; }
        public virtual DbSet<Spr_kompl> Spr_kompl { get; set; }
        public virtual DbSet<Spr_mash> Spr_mash { get; set; }
        public virtual DbSet<Spr_mash_sg> Spr_mash_sg { get; set; }
        public virtual DbSet<Spr_mater> Spr_mater { get; set; }
        public virtual DbSet<Spr_METODIC> Spr_METODIC { get; set; }
        public virtual DbSet<Spr_metrol> Spr_metrol { get; set; }
        public virtual DbSet<Spr_nm_task> Spr_nm_task { get; set; }
        public virtual DbSet<Spr_nmdet> Spr_nmdet { get; set; }
        public virtual DbSet<Spr_normali> Spr_normali { get; set; }
        public virtual DbSet<Spr_obozn> Spr_obozn { get; set; }
        public virtual DbSet<Spr_obozn_mater> Spr_obozn_mater { get; set; }
        public virtual DbSet<Spr_obraz> Spr_obraz { get; set; }
        public virtual DbSet<SPR_OGT> SPR_OGT { get; set; }
        public virtual DbSet<SPR_OTS> SPR_OTS { get; set; }
        public virtual DbSet<Spr_per_dok_ob> Spr_per_dok_ob { get; set; }
        public virtual DbSet<Spr_Perizd> Spr_Perizd { get; set; }
        public virtual DbSet<Spr_PKP> Spr_PKP { get; set; }
        public virtual DbSet<Spr_predel> Spr_predel { get; set; }
        public virtual DbSet<Spr_prim_dse> Spr_prim_dse { get; set; }
        public virtual DbSet<SPR_PRKM> SPR_PRKM { get; set; }
        public virtual DbSet<Spr_prpokr> Spr_prpokr { get; set; }
        public virtual DbSet<Spr_pvi> Spr_pvi { get; set; }
        public virtual DbSet<Spr_rasc_vert> Spr_rasc_vert { get; set; }
        public virtual DbSet<Spr_rascex> Spr_rascex { get; set; }
        public virtual DbSet<Spr_rascex_poln> Spr_rascex_poln { get; set; }
        public virtual DbSet<Spr_Razd_DSE> Spr_Razd_DSE { get; set; }
        public virtual DbSet<Spr_Razd_Izd> Spr_Razd_Izd { get; set; }
        public virtual DbSet<Spr_razd_izm> Spr_razd_izm { get; set; }
        public virtual DbSet<Spr_skm> Spr_skm { get; set; }
        public virtual DbSet<SPR_sortam> SPR_sortam { get; set; }
        public virtual DbSet<Spr_specif> Spr_specif { get; set; }
        public virtual DbSet<Spr_stan> Spr_stan { get; set; }
        public virtual DbSet<Spr_Tehnizg> Spr_Tehnizg { get; set; }
        public virtual DbSet<Spr_tehnol_izgot_proizv> Spr_tehnol_izgot_proizv { get; set; }
        public virtual DbSet<Spr_tem> Spr_tem { get; set; }
        public virtual DbSet<Spr_tematik> Spr_tematik { get; set; }
        public virtual DbSet<Spr_tto> Spr_tto { get; set; }
        public virtual DbSet<Spr_uch_cex> Spr_uch_cex { get; set; }
        public virtual DbSet<Spr_Zakaz> Spr_Zakaz { get; set; }
        public virtual DbSet<Status_dok> Status_dok { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<Tip_pribora> Tip_pribora { get; set; }
        public virtual DbSet<Trud_ob> Trud_ob { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Usl_expluat> Usl_expluat { get; set; }
        public virtual DbSet<Uvedomlenie_mater> Uvedomlenie_mater { get; set; }
        public virtual DbSet<Vid_izmer> Vid_izmer { get; set; }
        public virtual DbSet<Zayvka_mater> Zayvka_mater { get; set; }
        public virtual DbSet<Temp_Spr_eizm> Temp_Spr_eizm { get; set; }
    }
}
