//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Der_izd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Der_izd()
        {
            this.Der_izd1 = new HashSet<Der_izd>();
        }
    
        public long Id { get; set; }
        public Nullable<int> link_izd { get; set; }
        public Nullable<long> link_rod { get; set; }
        public Nullable<int> dlin { get; set; }
        public Nullable<int> sort { get; set; }
        public Nullable<long> link_komplekt { get; set; }
        public Nullable<long> link_kts { get; set; }
        public Nullable<long> link_obozn { get; set; }
        public Nullable<int> kol { get; set; }
        public string tk { get; set; }
        public Nullable<long> link_agr { get; set; }
        public Nullable<long> link_razdizd { get; set; }
        public Nullable<long> link_grrazdizd { get; set; }
        public string ss { get; set; }
        public string spo { get; set; }
        public string vhodim { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<int> link_user { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
    
        public virtual Spr_agr Spr_agr { get; set; }
        public virtual GR_RAZDIZD GR_RAZDIZD { get; set; }
        public virtual Spr_Perizd Spr_Perizd { get; set; }
        public virtual Spr_kompl Spr_kompl { get; set; }
        public virtual Spr_obozn Spr_obozn { get; set; }
        public virtual Spr_obozn Spr_obozn1 { get; set; }
        public virtual Raz_det Raz_det { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Der_izd> Der_izd1 { get; set; }
        public virtual Der_izd Der_izd2 { get; set; }
        public virtual Status_dok Status_dok { get; set; }
        public virtual User User { get; set; }
    }
}
