//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Der_btp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Der_btp()
        {
            this.Der_btp1 = new HashSet<Der_btp>();
        }
    
        public long Id { get; set; }
        public Nullable<long> link_rod { get; set; }
        public Nullable<int> dlin { get; set; }
        public Nullable<int> sort { get; set; }
        public Nullable<long> link_kts { get; set; }
        public Nullable<long> link_obozn { get; set; }
        public Nullable<int> kol { get; set; }
        public string tk { get; set; }
        public Nullable<long> link_agr { get; set; }
        public Nullable<int> link_izd { get; set; }
        public string sz { get; set; }
        public string n_specif { get; set; }
        public string zakaz { get; set; }
        public string serii { get; set; }
        public string bull { get; set; }
        public Nullable<int> nm_gr_sz { get; set; }
        public Nullable<int> poz { get; set; }
        public Nullable<int> list { get; set; }
        public string rascex { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<int> link_user { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Der_btp> Der_btp1 { get; set; }
        public virtual Der_btp Der_btp2 { get; set; }
    }
}
