//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image_old_v2
    {
        public int Id { get; set; }
        public byte[] screen { get; set; }
        public string name { get; set; }
        public string UrlAction { get; set; }
        public string Alt { get; set; }
        public string Controller_Name { get; set; }
        public string Action_Name { get; set; }
        public Nullable<bool> IsGroup { get; set; }
        public string RouteUrl { get; set; }
        public string Title { get; set; }
    }
}
