//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPR_OGT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPR_OGT()
        {
            this.Spr_skm = new HashSet<Spr_skm>();
        }
    
        public long Id { get; set; }
        public string naim_ogt { get; set; }
        public Nullable<int> OGT { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<int> link_user { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
        public Nullable<int> link_gr_mater { get; set; }
        public Nullable<long> link_prkm { get; set; }
        public Nullable<long> link_sort { get; set; }
        public Nullable<int> ksim_km { get; set; }
    
        public virtual Sort_Mater Sort_Mater { get; set; }
        public virtual Spr_GR_Mater Spr_GR_Mater { get; set; }
        public virtual SPR_PRKM SPR_PRKM { get; set; }
        public virtual Status_dok Status_dok { get; set; }
        public virtual User User { get; set; }
        public virtual SPR_OGT SPR_OGT1 { get; set; }
        public virtual SPR_OGT SPR_OGT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_skm> Spr_skm { get; set; }
    }
}
