//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spr_specif
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spr_specif()
        {
            this.Spr_prim_dse = new HashSet<Spr_prim_dse>();
        }
    
        public long Id { get; set; }
        public Nullable<long> link_kts { get; set; }
        public Nullable<long> link_obozn { get; set; }
        public Nullable<long> link_pkp_T_TV { get; set; }
        public Nullable<int> link_kdan { get; set; }
        public Nullable<long> link_razd_det { get; set; }
        public Nullable<int> ksb { get; set; }
        public Nullable<long> link_komplekt { get; set; }
        public string prim_texn { get; set; }
        public string prim_konstrukt { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<int> link_user { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
        public string prim_kts { get; set; }
        public Nullable<long> link_spec { get; set; }
        public Nullable<long> link_svyz_prim { get; set; }
    
        public virtual Raz_det Raz_det { get; set; }
        public virtual Spr_kdan Spr_kdan { get; set; }
        public virtual Spr_kompl Spr_kompl { get; set; }
        public virtual Spr_obozn Spr_obozn { get; set; }
        public virtual Spr_obozn Spr_obozn1 { get; set; }
        public virtual Spr_PKP Spr_PKP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_prim_dse> Spr_prim_dse { get; set; }
        public virtual Status_dok Status_dok { get; set; }
        public virtual User User { get; set; }
    }
}
