//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spr_dse
    {
        public long Id { get; set; }
        public Nullable<long> link_pkp { get; set; }
        public Nullable<long> link_obozn { get; set; }
        public Nullable<int> link_cex { get; set; }
        public Nullable<long> link_km { get; set; }
        public Nullable<long> link_nm_metodic { get; set; }
        public Nullable<long> link_prkm { get; set; }
        public Nullable<decimal> bz { get; set; }
        public Nullable<decimal> lz { get; set; }
        public Nullable<decimal> nr { get; set; }
        public Nullable<int> vpost { get; set; }
        public Nullable<decimal> nrvp { get; set; }
        public Nullable<long> link_primdse { get; set; }
        public Nullable<int> vpost_sh { get; set; }
        public Nullable<int> krat { get; set; }
        public string ndoc { get; set; }
        public Nullable<long> link_tema { get; set; }
        public Nullable<long> link_rascex { get; set; }
        public string ree { get; set; }
        public Nullable<bool> pr_got_ci { get; set; }
        public Nullable<bool> pr_othod { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<int> link_user { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
        public string prascr { get; set; }
        public Nullable<long> tehn_izgot { get; set; }
    
        public virtual Spr_cex Spr_cex { get; set; }
        public virtual Spr_skm Spr_skm { get; set; }
        public virtual Spr_METODIC Spr_METODIC { get; set; }
        public virtual Spr_obozn Spr_obozn { get; set; }
        public virtual Spr_PKP Spr_PKP { get; set; }
        public virtual Spr_prim_dse Spr_prim_dse { get; set; }
        public virtual SPR_PRKM SPR_PRKM { get; set; }
        public virtual Spr_rascex Spr_rascex { get; set; }
        public virtual Status_dok Status_dok { get; set; }
        public virtual Spr_tem Spr_tem { get; set; }
        public virtual User User { get; set; }
        public virtual Spr_Tehnizg Spr_Tehnizg { get; set; }
    }
}
