//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spr_metrol
    {
        public int Id { get; set; }
        public Nullable<int> link_podgrupp { get; set; }
        public Nullable<int> link_group { get; set; }
        public Nullable<int> link_naznach { get; set; }
        public Nullable<int> link_cex { get; set; }
        public Nullable<int> link_period_poverk { get; set; }
        public Nullable<int> link_mesto_poverk { get; set; }
        public Nullable<int> link_rod_poverk { get; set; }
        public Nullable<int> link_tip_pribora { get; set; }
        public Nullable<int> link_konserv { get; set; }
        public Nullable<decimal> n_pasporta { get; set; }
        public string n_zavod { get; set; }
        public Nullable<System.DateTime> data_pover { get; set; }
        public Nullable<System.DateTime> data_pred_pov { get; set; }
        public Nullable<int> link_usl { get; set; }
        public Nullable<int> link_ree { get; set; }
        public Nullable<int> link_stan { get; set; }
        public string god_vip { get; set; }
        public Nullable<int> link_predpr { get; set; }
        public Nullable<System.DateTime> data_izm { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<int> link_user { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
    
        public virtual Gos_ree Gos_ree { get; set; }
        public virtual Konserv Konserv { get; set; }
        public virtual M_Poverk M_Poverk { get; set; }
        public virtual Nazn_prib Nazn_prib { get; set; }
        public virtual Period_pover Period_pover { get; set; }
        public virtual Podgrupp Podgrupp { get; set; }
        public virtual Podgrupp Podgrupp1 { get; set; }
        public virtual Predpr_izg Predpr_izg { get; set; }
        public virtual Rod_poverk Rod_poverk { get; set; }
        public virtual Spr_cex Spr_cex { get; set; }
        public virtual Spr_stan Spr_stan { get; set; }
        public virtual Status_dok Status_dok { get; set; }
        public virtual Tip_pribora Tip_pribora { get; set; }
        public virtual Usl_expluat Usl_expluat { get; set; }
        public virtual User User { get; set; }
    }
}
