//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spr_PKP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spr_PKP()
        {
            this.Spr_dse = new HashSet<Spr_dse>();
            this.Spr_normali = new HashSet<Spr_normali>();
            this.Spr_obozn = new HashSet<Spr_obozn>();
            this.Spr_obraz = new HashSet<Spr_obraz>();
            this.Spr_specif = new HashSet<Spr_specif>();
            this.Trud_ob = new HashSet<Trud_ob>();
        }
    
        public long Id { get; set; }
        public string pkp { get; set; }
        public string nm_pkp { get; set; }
        public Nullable<long> link_razd { get; set; }
        public Nullable<long> link_razd_dse { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<int> link_user { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
        public string ImageFileName { get; set; }
        public string pkp_dos { get; set; }
    
        public virtual Raz_det Raz_det { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_dse> Spr_dse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_normali> Spr_normali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_obozn> Spr_obozn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_obraz> Spr_obraz { get; set; }
        public virtual Spr_Razd_DSE Spr_Razd_DSE { get; set; }
        public virtual Status_dok Status_dok { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_specif> Spr_specif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trud_ob> Trud_ob { get; set; }
    }
}
