//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spr_Perizd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spr_Perizd()
        {
            this.Der_izd = new HashSet<Der_izd>();
            this.GR_RAZDIZD = new HashSet<GR_RAZDIZD>();
            this.Spr_mash = new HashSet<Spr_mash>();
            this.Spr_mash_sg = new HashSet<Spr_mash_sg>();
            this.Spr_prim_dse = new HashSet<Spr_prim_dse>();
            this.Trud_ob = new HashSet<Trud_ob>();
        }
    
        public int Id { get; set; }
        public string izdelie { get; set; }
        public string kod_izd { get; set; }
        public string nm_izd { get; set; }
        public string ser_ss { get; set; }
        public string ser_spo { get; set; }
        public string kgk1_1 { get; set; }
        public string kgk1_n { get; set; }
        public string kgk1_m { get; set; }
        public string tek_ser_s { get; set; }
        public string tek_ser_po { get; set; }
        public Nullable<long> link_tema { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<int> link_user { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
        public Nullable<long> Model_tehnol_podgot_proizv { get; set; }
        public string prim { get; set; }
        public Nullable<long> link_tematik { get; set; }
        public string pr_komplektov { get; set; }
        public string soot_ss { get; set; }
        public string soot_spo { get; set; }
        public Nullable<long> link_zakaz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Der_izd> Der_izd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GR_RAZDIZD> GR_RAZDIZD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_mash> Spr_mash { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_mash_sg> Spr_mash_sg { get; set; }
        public virtual Status_dok Status_dok { get; set; }
        public virtual Spr_tem Spr_tem { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_prim_dse> Spr_prim_dse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trud_ob> Trud_ob { get; set; }
    }
}
