//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spr_prim_dse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spr_prim_dse()
        {
            this.Spr_dse = new HashSet<Spr_dse>();
            this.Spr_normali = new HashSet<Spr_normali>();
            this.Spr_per_dok_ob = new HashSet<Spr_per_dok_ob>();
        }
    
        public long Id { get; set; }
        public Nullable<long> link_specif { get; set; }
        public Nullable<int> link_izd { get; set; }
        public Nullable<long> link_grrazdizd { get; set; }
        public Nullable<int> kizd { get; set; }
        public Nullable<int> kp1 { get; set; }
        public Nullable<int> kp2 { get; set; }
        public Nullable<int> kp3 { get; set; }
        public string tk1 { get; set; }
        public string tk2 { get; set; }
        public string tk3 { get; set; }
        public Nullable<decimal> masizd { get; set; }
        public Nullable<long> link_rascizd { get; set; }
        public string ss { get; set; }
        public string spo { get; set; }
        public string n_list { get; set; }
        public string n_poz { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<int> link_user { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
        public Nullable<long> link_obozn { get; set; }
        public Nullable<int> CP1 { get; set; }
        public Nullable<int> CP2 { get; set; }
        public Nullable<int> CP3 { get; set; }
        public string rascex { get; set; }
        public Nullable<long> link_kts { get; set; }
        public Nullable<long> link_obozn_mater { get; set; }
    
        public virtual GR_RAZDIZD GR_RAZDIZD { get; set; }
        public virtual Spr_cex Spr_cex { get; set; }
        public virtual Spr_cex Spr_cex1 { get; set; }
        public virtual Spr_cex Spr_cex2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_dse> Spr_dse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_normali> Spr_normali { get; set; }
        public virtual Spr_obozn Spr_obozn { get; set; }
        public virtual Spr_obozn Spr_obozn1 { get; set; }
        public virtual Spr_obozn_mater Spr_obozn_mater { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_per_dok_ob> Spr_per_dok_ob { get; set; }
        public virtual Spr_Perizd Spr_Perizd { get; set; }
        public virtual Spr_rascex Spr_rascex { get; set; }
        public virtual Spr_specif Spr_specif { get; set; }
        public virtual Status_dok Status_dok { get; set; }
        public virtual User User { get; set; }
    }
}
