//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spr_Zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spr_Zakaz()
        {
            this.GR_RAZDIZD = new HashSet<GR_RAZDIZD>();
            this.Spr_mash = new HashSet<Spr_mash>();
            this.Spr_mash_sg = new HashSet<Spr_mash_sg>();
        }
    
        public long Id { get; set; }
        public string zakaz { get; set; }
        public string nm_zakaz { get; set; }
        public Nullable<System.DateTime> zakaz_open_date { get; set; }
        public Nullable<System.DateTime> zakaz_close_date { get; set; }
        public string osnovanie { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
        public Nullable<int> link_user { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GR_RAZDIZD> GR_RAZDIZD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_mash> Spr_mash { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_mash_sg> Spr_mash_sg { get; set; }
        public virtual Status_dok Status_dok { get; set; }
        public virtual User User { get; set; }
    }
}
