//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spr_tto
    {
        public long Id { get; set; }
        public Nullable<long> link_kod_TTO { get; set; }
        public Nullable<long> link_kod_komp { get; set; }
        public Nullable<int> link_cizg { get; set; }
        public Nullable<long> link_prkm { get; set; }
        public Nullable<long> link_prpokr { get; set; }
        public Nullable<decimal> nrm { get; set; }
        public Nullable<int> vpost { get; set; }
        public Nullable<decimal> nrvp { get; set; }
        public Nullable<int> krat { get; set; }
        public Nullable<int> vpost_sh { get; set; }
        public Nullable<int> sort_kod_TTO { get; set; }
        public Nullable<int> sort_kod_komp { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<int> link_user { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
    
        public virtual Spr_cex Spr_cex { get; set; }
        public virtual SPR_PRKM SPR_PRKM { get; set; }
        public virtual Spr_prpokr Spr_prpokr { get; set; }
        public virtual Spr_skm Spr_skm { get; set; }
        public virtual Spr_skm Spr_skm1 { get; set; }
        public virtual Status_dok Status_dok { get; set; }
        public virtual User User { get; set; }
    }
}
