//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spr_cex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spr_cex()
        {
            this.Spr_cex1 = new HashSet<Spr_cex>();
            this.Spr_dse = new HashSet<Spr_dse>();
            this.Spr_metrol = new HashSet<Spr_metrol>();
            this.Spr_normali = new HashSet<Spr_normali>();
            this.Spr_obraz = new HashSet<Spr_obraz>();
            this.Spr_prim_dse = new HashSet<Spr_prim_dse>();
            this.Spr_prim_dse1 = new HashSet<Spr_prim_dse>();
            this.Spr_prim_dse2 = new HashSet<Spr_prim_dse>();
            this.Spr_rascex = new HashSet<Spr_rascex>();
            this.Spr_rascex1 = new HashSet<Spr_rascex>();
            this.Spr_rascex2 = new HashSet<Spr_rascex>();
            this.Spr_rascex3 = new HashSet<Spr_rascex>();
            this.Spr_rascex4 = new HashSet<Spr_rascex>();
            this.Spr_rascex5 = new HashSet<Spr_rascex>();
            this.Spr_rascex6 = new HashSet<Spr_rascex>();
            this.Spr_rascex7 = new HashSet<Spr_rascex>();
            this.Spr_rascex8 = new HashSet<Spr_rascex>();
            this.Spr_rascex9 = new HashSet<Spr_rascex>();
            this.Spr_rascex10 = new HashSet<Spr_rascex>();
            this.Spr_rascex11 = new HashSet<Spr_rascex>();
            this.Spr_rascex12 = new HashSet<Spr_rascex>();
            this.Spr_rascex13 = new HashSet<Spr_rascex>();
            this.Spr_rascex14 = new HashSet<Spr_rascex>();
            this.Spr_rascex15 = new HashSet<Spr_rascex>();
            this.Spr_rascex16 = new HashSet<Spr_rascex>();
            this.Spr_rascex17 = new HashSet<Spr_rascex>();
            this.Spr_rascex18 = new HashSet<Spr_rascex>();
            this.Spr_rascex19 = new HashSet<Spr_rascex>();
            this.Spr_rascex20 = new HashSet<Spr_rascex>();
            this.Spr_rascex21 = new HashSet<Spr_rascex>();
            this.Spr_rascex22 = new HashSet<Spr_rascex>();
            this.Spr_rascex23 = new HashSet<Spr_rascex>();
            this.Spr_rascex24 = new HashSet<Spr_rascex>();
            this.Spr_rascex25 = new HashSet<Spr_rascex>();
            this.Spr_rascex26 = new HashSet<Spr_rascex>();
            this.Spr_rascex_poln = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln1 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln2 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln3 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln4 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln5 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln6 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln7 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln8 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln9 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln10 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln11 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln12 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln13 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln14 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln15 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln16 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln17 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln18 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln19 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln20 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln21 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln22 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln23 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln24 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln25 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln26 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln27 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln28 = new HashSet<Spr_rascex_poln>();
            this.Spr_rascex_poln29 = new HashSet<Spr_rascex_poln>();
            this.Spr_tto = new HashSet<Spr_tto>();
            this.Spr_uch_cex = new HashSet<Spr_uch_cex>();
            this.Trud_ob = new HashSet<Trud_ob>();
            this.User1 = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string cex { get; set; }
        public string naim_cex { get; set; }
        public Nullable<int> link_status { get; set; }
        public string nm_cex_krat { get; set; }
        public Nullable<int> link_user { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
        public Nullable<int> link_cex_real { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_cex> Spr_cex1 { get; set; }
        public virtual Spr_cex Spr_cex2 { get; set; }
        public virtual Status_dok Status_dok { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_dse> Spr_dse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_metrol> Spr_metrol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_normali> Spr_normali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_obraz> Spr_obraz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_prim_dse> Spr_prim_dse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_prim_dse> Spr_prim_dse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_prim_dse> Spr_prim_dse2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex20 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex23 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex24 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex25 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex26 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln20 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln23 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln24 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln25 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln26 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln27 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln28 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln29 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_tto> Spr_tto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_uch_cex> Spr_uch_cex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trud_ob> Trud_ob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User1 { get; set; }
    }
}
