//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spr_obozn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spr_obozn()
        {
            this.Der_izd = new HashSet<Der_izd>();
            this.Der_izd1 = new HashSet<Der_izd>();
            this.GR_RAZDIZD = new HashSet<GR_RAZDIZD>();
            this.Spr_dse = new HashSet<Spr_dse>();
            this.Spr_normali = new HashSet<Spr_normali>();
            this.Spr_obozn_mater = new HashSet<Spr_obozn_mater>();
            this.Spr_obraz = new HashSet<Spr_obraz>();
            this.Spr_prim_dse = new HashSet<Spr_prim_dse>();
            this.Spr_prim_dse1 = new HashSet<Spr_prim_dse>();
            this.Spr_specif = new HashSet<Spr_specif>();
            this.Spr_specif1 = new HashSet<Spr_specif>();
            this.Trud_ob = new HashSet<Trud_ob>();
        }
    
        public long Id { get; set; }
        public string obozn { get; set; }
        public string var { get; set; }
        public Nullable<long> link_pkp { get; set; }
        public Nullable<long> link_naim { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<int> link_user { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
        public string obozn_p { get; set; }
        public string obozn_dos { get; set; }
        public string stsort_kt { get; set; }
        public string stsort_tip { get; set; }
        public string stsort_tr_1 { get; set; }
        public string stsort_tr_2 { get; set; }
        public string stsort_tr_3 { get; set; }
        public string stsort_tr_4 { get; set; }
        public string stsort_tr_5 { get; set; }
        public string stsort_tr_6 { get; set; }
        public string stsort_tr_7 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Der_izd> Der_izd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Der_izd> Der_izd1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GR_RAZDIZD> GR_RAZDIZD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_dse> Spr_dse { get; set; }
        public virtual Spr_nmdet Spr_nmdet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_normali> Spr_normali { get; set; }
        public virtual Spr_PKP Spr_PKP { get; set; }
        public virtual Status_dok Status_dok { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_obozn_mater> Spr_obozn_mater { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_obraz> Spr_obraz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_prim_dse> Spr_prim_dse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_prim_dse> Spr_prim_dse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_specif> Spr_specif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_specif> Spr_specif1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trud_ob> Trud_ob { get; set; }
    }
}
