//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spr_mash_sg
    {
        public long Id { get; set; }
        public string nom_mash { get; set; }
        public string naim_mash { get; set; }
        public Nullable<int> link_izd { get; set; }
        public string ser_s { get; set; }
        public string ser_po { get; set; }
        public Nullable<long> link_zakaz { get; set; }
        public Nullable<int> kol_kompl { get; set; }
        public Nullable<int> shag { get; set; }
        public Nullable<int> gr_kol { get; set; }
        public Nullable<int> pr_zrasc { get; set; }
        public Nullable<int> pr_kompl { get; set; }
        public string ud_ss { get; set; }
        public string ud_spo { get; set; }
        public string soot_s { get; set; }
        public string soot_po { get; set; }
        public string soot_ud_ss { get; set; }
        public string soot_ud_spo { get; set; }
        public string kompl1 { get; set; }
        public string kompl2 { get; set; }
        public string sort { get; set; }
        public string rspo { get; set; }
        public Nullable<int> kmash { get; set; }
        public string kod_o { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<int> link_user { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
    
        public virtual Spr_Perizd Spr_Perizd { get; set; }
        public virtual Status_dok Status_dok { get; set; }
        public virtual User User { get; set; }
        public virtual Spr_Zakaz Spr_Zakaz { get; set; }
    }
}
