//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spr_rascex_poln
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spr_rascex_poln()
        {
            this.Spr_rasc_vert = new HashSet<Spr_rasc_vert>();
        }
    
        public long Id { get; set; }
        public Nullable<long> link_rascex { get; set; }
        public Nullable<int> CI11 { get; set; }
        public Nullable<int> CP1 { get; set; }
        public Nullable<int> CI12 { get; set; }
        public Nullable<int> CP2 { get; set; }
        public Nullable<int> CI13 { get; set; }
        public Nullable<int> CP3 { get; set; }
        public Nullable<int> CI2 { get; set; }
        public Nullable<int> CI3 { get; set; }
        public Nullable<int> CI4 { get; set; }
        public Nullable<int> CI5 { get; set; }
        public Nullable<int> CI6 { get; set; }
        public Nullable<int> CI7 { get; set; }
        public Nullable<int> CTO { get; set; }
        public Nullable<int> CPK1 { get; set; }
        public Nullable<int> CPK2 { get; set; }
        public Nullable<int> CPK3 { get; set; }
        public Nullable<int> CPK4 { get; set; }
        public Nullable<int> CUS1 { get; set; }
        public Nullable<int> CUS2 { get; set; }
        public Nullable<int> CUS3 { get; set; }
        public Nullable<int> CUS4 { get; set; }
        public Nullable<int> CUS5 { get; set; }
        public Nullable<int> CUS6 { get; set; }
        public Nullable<int> CUS7 { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<int> link_user { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
        public Nullable<int> CI8 { get; set; }
        public Nullable<int> CI9 { get; set; }
        public Nullable<int> CI10 { get; set; }
        public Nullable<int> CUS8 { get; set; }
        public Nullable<int> CUS9 { get; set; }
        public Nullable<int> CUS10 { get; set; }
        public string rascex_small { get; set; }
    
        public virtual Spr_cex Spr_cex { get; set; }
        public virtual Spr_cex Spr_cex1 { get; set; }
        public virtual Spr_cex Spr_cex2 { get; set; }
        public virtual Spr_cex Spr_cex3 { get; set; }
        public virtual Spr_cex Spr_cex4 { get; set; }
        public virtual Spr_cex Spr_cex5 { get; set; }
        public virtual Spr_cex Spr_cex6 { get; set; }
        public virtual Spr_cex Spr_cex7 { get; set; }
        public virtual Spr_cex Spr_cex8 { get; set; }
        public virtual Spr_cex Spr_cex9 { get; set; }
        public virtual Spr_cex Spr_cex10 { get; set; }
        public virtual Spr_cex Spr_cex11 { get; set; }
        public virtual Spr_cex Spr_cex12 { get; set; }
        public virtual Spr_cex Spr_cex13 { get; set; }
        public virtual Spr_cex Spr_cex14 { get; set; }
        public virtual Spr_cex Spr_cex15 { get; set; }
        public virtual Spr_cex Spr_cex16 { get; set; }
        public virtual Spr_cex Spr_cex17 { get; set; }
        public virtual Spr_cex Spr_cex18 { get; set; }
        public virtual Spr_cex Spr_cex19 { get; set; }
        public virtual Spr_cex Spr_cex20 { get; set; }
        public virtual Spr_cex Spr_cex21 { get; set; }
        public virtual Spr_cex Spr_cex22 { get; set; }
        public virtual Spr_cex Spr_cex23 { get; set; }
        public virtual Spr_cex Spr_cex24 { get; set; }
        public virtual Spr_cex Spr_cex25 { get; set; }
        public virtual Spr_cex Spr_cex26 { get; set; }
        public virtual Spr_cex Spr_cex27 { get; set; }
        public virtual Spr_cex Spr_cex28 { get; set; }
        public virtual Spr_cex Spr_cex29 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rasc_vert> Spr_rasc_vert { get; set; }
        public virtual Spr_rascex Spr_rascex { get; set; }
        public virtual Status_dok Status_dok { get; set; }
        public virtual User User { get; set; }
    }
}
