//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spr_rasc_vert
    {
        public long Id { get; set; }
        public Nullable<long> link_rascex_poln { get; set; }
        public Nullable<decimal> npp { get; set; }
        public Nullable<int> link_cex { get; set; }
        public Nullable<long> link_cex_prizn { get; set; }
        public Nullable<bool> pr_cex_osn { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<int> link_user { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
        public Nullable<int> link_cex_potr { get; set; }
    
        public virtual Spr_cex_prizn Spr_cex_prizn { get; set; }
        public virtual Spr_rascex_poln Spr_rascex_poln { get; set; }
        public virtual Status_dok Status_dok { get; set; }
        public virtual User User { get; set; }
    }
}
