//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spr_skm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spr_skm()
        {
            this.Spr_dse = new HashSet<Spr_dse>();
            this.Spr_normali = new HashSet<Spr_normali>();
            this.Spr_obraz = new HashSet<Spr_obraz>();
            this.Spr_tto = new HashSet<Spr_tto>();
            this.Spr_tto1 = new HashSet<Spr_tto>();
        }
    
        public long Id { get; set; }
        public string km { get; set; }
        public string dbt { get; set; }
        public string dsh { get; set; }
        public Nullable<decimal> ves { get; set; }
        public Nullable<long> link_nm_skm { get; set; }
        public Nullable<long> link_marka { get; set; }
        public Nullable<long> link_gost { get; set; }
        public Nullable<long> link_eizm { get; set; }
        public Nullable<long> link_kgr { get; set; }
        public Nullable<long> link_ots { get; set; }
        public Nullable<long> link_ogt { get; set; }
        public Nullable<long> link_balsch { get; set; }
        public Nullable<long> link_prkm { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<int> link_user { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
        public Nullable<int> link_GR_Mater { get; set; }
        public string nomenkl_nomer { get; set; }
        public Nullable<int> sort_OGT { get; set; }
    
        public virtual GOST_mater GOST_mater { get; set; }
        public virtual Mark_mater Mark_mater { get; set; }
        public virtual Nm_mater Nm_mater { get; set; }
        public virtual Spr_balsch Spr_balsch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_dse> Spr_dse { get; set; }
        public virtual Spr_eizm Spr_eizm { get; set; }
        public virtual Spr_GR_Mater Spr_GR_Mater { get; set; }
        public virtual Spr_kgr Spr_kgr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_normali> Spr_normali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_obraz> Spr_obraz { get; set; }
        public virtual SPR_OGT SPR_OGT { get; set; }
        public virtual SPR_OTS SPR_OTS { get; set; }
        public virtual SPR_PRKM SPR_PRKM { get; set; }
        public virtual Status_dok Status_dok { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_tto> Spr_tto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_tto> Spr_tto1 { get; set; }
    }
}
