//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Spr_eizm
    {
        public long Id { get; set; }
        public string krat_naim_eizm { get; set; }
        public string poln_naim_eizm { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<int> link_user { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
    }
}
