//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trud_ob
    {
        public long Id { get; set; }
        public Nullable<int> link_izd { get; set; }
        public Nullable<long> link_pkp { get; set; }
        public Nullable<int> link_cex { get; set; }
        public Nullable<long> link_obozn { get; set; }
        public Nullable<int> uchastok { get; set; }
        public Nullable<int> vidrabot { get; set; }
        public Nullable<decimal> tr_sdel { get; set; }
        public Nullable<decimal> rascen { get; set; }
        public Nullable<decimal> tr_povr { get; set; }
        public string ndok { get; set; }
        public string vidrab_izg_usl { get; set; }
        public string vidrabi { get; set; }
        public string prim { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<int> link_user { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
    
        public virtual Spr_cex Spr_cex { get; set; }
        public virtual Spr_obozn Spr_obozn { get; set; }
        public virtual Spr_Perizd Spr_Perizd { get; set; }
        public virtual Spr_PKP Spr_PKP { get; set; }
        public virtual Status_dok Status_dok { get; set; }
        public virtual User User { get; set; }
    }
}
