//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Der_izd = new HashSet<Der_izd>();
            this.Dokum_Obosnov = new HashSet<Dokum_Obosnov>();
            this.Gos_ree = new HashSet<Gos_ree>();
            this.GOST_mater = new HashSet<GOST_mater>();
            this.GR_RAZDIZD = new HashSet<GR_RAZDIZD>();
            this.Grupp = new HashSet<Grupp>();
            this.Image_old = new HashSet<Image_old>();
            this.Konserv = new HashSet<Konserv>();
            this.M_Poverk = new HashSet<M_Poverk>();
            this.Mark_mater = new HashSet<Mark_mater>();
            this.Nazn_prib = new HashSet<Nazn_prib>();
            this.Nm_mater = new HashSet<Nm_mater>();
            this.Nm_prib = new HashSet<Nm_prib>();
            this.Nm_vidiz = new HashSet<Nm_vidiz>();
            this.Period_pover = new HashSet<Period_pover>();
            this.Podgr_prib = new HashSet<Podgr_prib>();
            this.Podgrupp = new HashSet<Podgrupp>();
            this.Predpr_izg = new HashSet<Predpr_izg>();
            this.Predpr_Postav = new HashSet<Predpr_Postav>();
            this.Raz_det = new HashSet<Raz_det>();
            this.Rod_poverk = new HashSet<Rod_poverk>();
            this.Role = new HashSet<Role>();
            this.Role_Mapping = new HashSet<Role_Mapping>();
            this.Sort_Mater = new HashSet<Sort_Mater>();
            this.Spr_agr = new HashSet<Spr_agr>();
            this.Spr_balsch = new HashSet<Spr_balsch>();
            this.Spr_cen_mater = new HashSet<Spr_cen_mater>();
            this.Spr_cena_del = new HashSet<Spr_cena_del>();
            this.Spr_cex = new HashSet<Spr_cex>();
            this.Spr_cex_prizn = new HashSet<Spr_cex_prizn>();
            this.Spr_dse = new HashSet<Spr_dse>();
            this.Spr_eizm = new HashSet<Spr_eizm>();
            this.Spr_GR_Mater = new HashSet<Spr_GR_Mater>();
            this.Spr_GR_tematik = new HashSet<Spr_GR_tematik>();
            this.Spr_kdan = new HashSet<Spr_kdan>();
            this.Spr_kgr = new HashSet<Spr_kgr>();
            this.Spr_klass_tochn = new HashSet<Spr_klass_tochn>();
            this.Spr_kompl = new HashSet<Spr_kompl>();
            this.Spr_mash = new HashSet<Spr_mash>();
            this.Spr_mash_sg = new HashSet<Spr_mash_sg>();
            this.Spr_mater = new HashSet<Spr_mater>();
            this.Spr_METODIC = new HashSet<Spr_METODIC>();
            this.Spr_metrol = new HashSet<Spr_metrol>();
            this.Spr_nm_task = new HashSet<Spr_nm_task>();
            this.Spr_nmdet = new HashSet<Spr_nmdet>();
            this.Spr_normali = new HashSet<Spr_normali>();
            this.Spr_obozn = new HashSet<Spr_obozn>();
            this.Spr_obozn_mater = new HashSet<Spr_obozn_mater>();
            this.Spr_obraz = new HashSet<Spr_obraz>();
            this.SPR_OGT = new HashSet<SPR_OGT>();
            this.SPR_OTS = new HashSet<SPR_OTS>();
            this.Spr_per_dok_ob = new HashSet<Spr_per_dok_ob>();
            this.Spr_Perizd = new HashSet<Spr_Perizd>();
            this.Spr_PKP = new HashSet<Spr_PKP>();
            this.Spr_predel = new HashSet<Spr_predel>();
            this.Spr_prim_dse = new HashSet<Spr_prim_dse>();
            this.SPR_PRKM = new HashSet<SPR_PRKM>();
            this.Spr_prpokr = new HashSet<Spr_prpokr>();
            this.Spr_pvi = new HashSet<Spr_pvi>();
            this.Spr_rasc_vert = new HashSet<Spr_rasc_vert>();
            this.Spr_rascex = new HashSet<Spr_rascex>();
            this.Spr_rascex_poln = new HashSet<Spr_rascex_poln>();
            this.Spr_Razd_DSE = new HashSet<Spr_Razd_DSE>();
            this.Spr_Razd_Izd = new HashSet<Spr_Razd_Izd>();
            this.Spr_razd_izm = new HashSet<Spr_razd_izm>();
            this.Spr_skm = new HashSet<Spr_skm>();
            this.SPR_sortam = new HashSet<SPR_sortam>();
            this.Spr_specif = new HashSet<Spr_specif>();
            this.Spr_stan = new HashSet<Spr_stan>();
            this.Spr_Tehnizg = new HashSet<Spr_Tehnizg>();
            this.Spr_tehnol_izgot_proizv = new HashSet<Spr_tehnol_izgot_proizv>();
            this.Spr_tem = new HashSet<Spr_tem>();
            this.Spr_tematik = new HashSet<Spr_tematik>();
            this.Spr_tto = new HashSet<Spr_tto>();
            this.Spr_uch_cex = new HashSet<Spr_uch_cex>();
            this.Spr_Zakaz = new HashSet<Spr_Zakaz>();
            this.Status_dok = new HashSet<Status_dok>();
            this.Tasks = new HashSet<Tasks>();
            this.Tip_pribora = new HashSet<Tip_pribora>();
            this.Trud_ob = new HashSet<Trud_ob>();
            this.Usl_expluat = new HashSet<Usl_expluat>();
            this.Uvedomlenie_mater = new HashSet<Uvedomlenie_mater>();
            this.Uvedomlenie_mater1 = new HashSet<Uvedomlenie_mater>();
            this.Vid_izmer = new HashSet<Vid_izmer>();
            this.Zayvka_mater = new HashSet<Zayvka_mater>();
        }
    
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public Nullable<int> link_cex { get; set; }
        public Nullable<System.DateTime> date_registr { get; set; }
        public Nullable<System.DateTime> date_visit { get; set; }
        public byte[] screen { get; set; }
        public byte[] Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Der_izd> Der_izd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokum_Obosnov> Dokum_Obosnov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gos_ree> Gos_ree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOST_mater> GOST_mater { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GR_RAZDIZD> GR_RAZDIZD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grupp> Grupp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image_old> Image_old { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konserv> Konserv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_Poverk> M_Poverk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mark_mater> Mark_mater { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nazn_prib> Nazn_prib { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nm_mater> Nm_mater { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nm_prib> Nm_prib { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nm_vidiz> Nm_vidiz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Period_pover> Period_pover { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Podgr_prib> Podgr_prib { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Podgrupp> Podgrupp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predpr_izg> Predpr_izg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predpr_Postav> Predpr_Postav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Raz_det> Raz_det { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rod_poverk> Rod_poverk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role_Mapping> Role_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sort_Mater> Sort_Mater { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_agr> Spr_agr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_balsch> Spr_balsch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_cen_mater> Spr_cen_mater { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_cena_del> Spr_cena_del { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_cex> Spr_cex { get; set; }
        public virtual Spr_cex Spr_cex1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_cex_prizn> Spr_cex_prizn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_dse> Spr_dse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_eizm> Spr_eizm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_GR_Mater> Spr_GR_Mater { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_GR_tematik> Spr_GR_tematik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_kdan> Spr_kdan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_kgr> Spr_kgr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_klass_tochn> Spr_klass_tochn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_kompl> Spr_kompl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_mash> Spr_mash { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_mash_sg> Spr_mash_sg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_mater> Spr_mater { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_METODIC> Spr_METODIC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_metrol> Spr_metrol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_nm_task> Spr_nm_task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_nmdet> Spr_nmdet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_normali> Spr_normali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_obozn> Spr_obozn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_obozn_mater> Spr_obozn_mater { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_obraz> Spr_obraz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPR_OGT> SPR_OGT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPR_OTS> SPR_OTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_per_dok_ob> Spr_per_dok_ob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_Perizd> Spr_Perizd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_PKP> Spr_PKP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_predel> Spr_predel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_prim_dse> Spr_prim_dse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPR_PRKM> SPR_PRKM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_prpokr> Spr_prpokr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_pvi> Spr_pvi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rasc_vert> Spr_rasc_vert { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex> Spr_rascex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_rascex_poln> Spr_rascex_poln { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_Razd_DSE> Spr_Razd_DSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_Razd_Izd> Spr_Razd_Izd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_razd_izm> Spr_razd_izm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_skm> Spr_skm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPR_sortam> SPR_sortam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_specif> Spr_specif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_stan> Spr_stan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_Tehnizg> Spr_Tehnizg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_tehnol_izgot_proizv> Spr_tehnol_izgot_proizv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_tem> Spr_tem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_tematik> Spr_tematik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_tto> Spr_tto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_uch_cex> Spr_uch_cex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_Zakaz> Spr_Zakaz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Status_dok> Status_dok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tasks> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tip_pribora> Tip_pribora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trud_ob> Trud_ob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usl_expluat> Usl_expluat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uvedomlenie_mater> Uvedomlenie_mater { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uvedomlenie_mater> Uvedomlenie_mater1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vid_izmer> Vid_izmer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zayvka_mater> Zayvka_mater { get; set; }
    }
}
