//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asu.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayvka_mater
    {
        public long Id { get; set; }
        public string kod_TTO { get; set; }
        public string kod_komp { get; set; }
        public string cizg { get; set; }
        public string prkm { get; set; }
        public string prpokr { get; set; }
        public Nullable<decimal> nrm { get; set; }
        public Nullable<int> vpost { get; set; }
        public Nullable<decimal> nrvp { get; set; }
        public Nullable<int> krat { get; set; }
        public Nullable<int> vpost_sh { get; set; }
        public string prim { get; set; }
        public Nullable<int> link_status { get; set; }
        public Nullable<int> link_user { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_date { get; set; }
        public Nullable<System.DateTime> period_open_date { get; set; }
        public Nullable<System.DateTime> period_close_date { get; set; }
    
        public virtual Status_dok Status_dok { get; set; }
        public virtual User User { get; set; }
    }
}
